version: '3'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55w0rd"
    ports:
      - "1433:1433"
  api:
    build: .
    ports:
      - "8080:80"